beers/urls.py
from django.urls import path, re_path
from . import views

app_name = 'beers'

urlpatterns = [
    path('', views.brewery, name='brewery'),
    re_path(r'(?P<brewery_id>[0-9]+)/favorite/$', views.favorite, name='favorite'),
    re_path(r'(?P<brewery_id>[0-9]+)/$', views.brewery_details, name='brewery_details'),
]

beerweb/urls.py
from django.contrib import admin
from django.urls import path

from beers import views
from django.conf.urls import include
from . import views

urlpatterns = [
    path('', views.index),
    path('admin/', admin.site.urls),
    path('brewery/', include('beers.urls'))
]

beers/models.py
from django.db import models

class Brewery(models.Model):
    name = models.CharField(max_length=250, blank= False, null=False)

    def __str__(self):
        return self.name


class BeerType(models.Model):
    beer_type = models.CharField(max_length=250, blank= False, null=False)

    def __str__(self):
        return self.beer_type


class Beer(models.Model):
    name = models.CharField(max_length=250, blank= False, null=False)
    ibu = models.IntegerField(null=True, blank=True)
    abv = models.FloatField(null=True, blank=True)
    brewery = models.ForeignKey(Brewery, null=True, on_delete=models.CASCADE)
    beer_type = models.ForeignKey(BeerType, null=True, on_delete=models.SET_NULL)
    is_favorite = models.BooleanField(default=False)

    def __str__(self):
        return self.name

beers/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse, Http404
from beers.models import Brewery, Beer

def index(request):
    return HttpResponse("hola cerveza")


def brewery(request):
    all_breweries = Brewery.objects.all()
    return render(request,'beers/breweries.html', {'pikachu': all_breweries})


def brewery_details(request, brewery_id):
    brewery = get_object_or_404(Brewery, pk=brewery_id)
    return render(request,'beers/details.html', {'brewery': brewery})


def favorite(request, brewery_id):
    brewery = get_object_or_404(Brewery, pk=brewery_id)
    try:
        selected_beer = brewery.beer_set.get(pk=request.POST['beer'])
    except (KeyError, Beer.DoesNotExist):
        return render(request,'beers/details.html', {
            'brewery': brewery,
            'error_message': 'No seleccionaste una cerveza válida'
            })
    else:
        selected_beer.is_favorite = True if not selected_beer.is_favorite else False
        selected_beer.save()
        return render(request,'beers/details.html', {'brewery': brewery})

beerweb/views.py
from django.shortcuts import render

def index(request):
    return render(request,'index.html')

templates/beers/breweries.html
{% if pikachu %}
<ul>
    {% for brewery in pikachu %}
        <li><a href="{% url 'beers:brewery_details' brewery.id %}"> {{ brewery.name }} </a><br></li>
    {% endfor %}
</ul>
{% else %}
    <p>No hay cervecerias</p>
{% endif %}

templates/beers/details.html
<h2>Cerveceria: {{ brewery }}</h2>


{% if error_message %}
    <p>
        {{ error_message }}
    </p>
{% endif %}


<p>
    Catalogo de cervezas:
</p>

<form action="{% url 'beers:favorite' brewery.id %}" method="POST">
    {% csrf_token %}
    {% for beer in brewery.beer_set.all %}
        <input type='radio' id="beer{{ forloop.counter }}" name="beer" value="{{ beer.id }}">
        <label for="beer{{ forloop.counter }}" >
            {{beer.name}}
            {% if beer.is_favorite %}
                <img src="https://i.imgur.com/b9b13Rd.png" />
            {% endif %}
        </label><br>
    {% endfor %}
    <input type="submit" value="Favorite">
</form>

<!-- <ul>
    {% for beer in brewery.beer_set.all %}
        <li>{{beer.name}}</li>
    {% endfor %}
</ul> -->

templates/index.html
<h1>BeerWeb</h1>
<p>La web para cerveceros con clase</p>